[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-python-crud-app"
version = "0.1.0"
description = "A Python Mongo CRUD application"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
dependencies = [
    "pymongo>=4.0.0",
    "flask>=2.0.0"
]
