name: Build, Check Artifact, and Upload (Python)

on:
  workflow_dispatch:

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Verify build output
        run: |
          if [ ! -d dist ]; then
            echo "No dist directory found!"
            exit 1
          else
            echo "dist folder found:"
            ls -lh dist
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-build
          path: dist/
